In [1]:
## import pandas 
import pandas as pd

In [2]:
## import dataset
df = pd.read_csv('NYCHA-mold-violations.csv')
df

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Order Number,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020)
0,18223816,286990,3,BROOKLYN,621,615,621,EAST 105 STREET,11236,BREUKELEN,...,550,N,40.650186,-73.897621,318,42,3321415,3081740001,982,BK1803
1,18311210,804658,1,MANHATTAN,218,218,220,EAST 115 STREET,10029,JEFFERSON,...,550,N,40.796972,-73.939869,111,8,1080706,1016620001,180,MN1102
2,18259184,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,Y,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
3,18235897,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,N,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
4,18235898,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,N,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,18652131,120460,2,BRONX,1320,1318,1332,WEBSTER AVENUE,10456,BUTLER,...,550,N,40.834189,-73.908540,203,16,2092074,2028940001,14701,BX0302
105,18654935,847216,3,BROOKLYN,542,542,546,FLUSHING AVENUE,11206,MARCY,...,501,N,40.699583,-73.951735,303,36,3325581,3017190001,255,BK0301
106,18662256,972853,1,MANHATTAN,3150,3140,3150,BROADWAY,10027,GRANT,...,550,N,40.814239,-73.959336,109,7,1084117,1019800001,211,MN0901
107,18635496,808526,3,BROOKLYN,811,811,817,HICKS STREET,11231,RED HOOK EAST,...,550,N,40.675324,-74.005451,306,38,3332230,3005380001,85,BK0601
108,18639299,807814,3,BROOKLYN,198,198,198,BOND STREET,11217,GOWANUS,...,550,N,40.683171,-73.987413,306,39,3323300,3003920001,71,BK0601

In [3]:
df.head()

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Order Number,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020)
0,18223816,286990,3,BROOKLYN,621,615,621,EAST 105 STREET,11236,BREUKELEN,...,550,N,40.650186,-73.897621,318,42,3321415,3081740001,982,BK1803
1,18311210,804658,1,MANHATTAN,218,218,220,EAST 115 STREET,10029,JEFFERSON,...,550,N,40.796972,-73.939869,111,8,1080706,1016620001,180,MN1102
2,18259184,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,Y,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
3,18235897,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,N,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
4,18235898,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,N,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901

In [4]:
df.tail()

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Order Number,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020)
104,18652131,120460,2,BRONX,1320,1318,1332,WEBSTER AVENUE,10456,BUTLER,...,550,N,40.834189,-73.908540,203,16,2092074,2028940001,14701,BX0302
105,18654935,847216,3,BROOKLYN,542,542,546,FLUSHING AVENUE,11206,MARCY,...,501,N,40.699583,-73.951735,303,36,3325581,3017190001,255,BK0301
106,18662256,972853,1,MANHATTAN,3150,3140,3150,BROADWAY,10027,GRANT,...,550,N,40.814239,-73.959336,109,7,1084117,1019800001,211,MN0901
107,18635496,808526,3,BROOKLYN,811,811,817,HICKS STREET,11231,RED HOOK EAST,...,550,N,40.675324,-74.005451,306,38,3332230,3005380001,85,BK0601
108,18639299,807814,3,BROOKLYN,198,198,198,BOND STREET,11217,GOWANUS,...,550,N,40.683171,-73.987413,306,39,3323300,3003920001,71,BK0601

In [8]:
df.sample(10)

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Order Number,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020)
85,18510185,811708,4,QUEENS,116-40,116-40,116-44,GUY R BREWER BOULEVARD,11434,BAISLEY PARK,...,550,N,40.685658,-73.783843,412,28,4435280,4122350022,278,QN1203
96,18654928,847216,3,BROOKLYN,542,542,546,FLUSHING AVENUE,11206,MARCY,...,550,N,40.699583,-73.951735,303,36,3325581,3017190001,255,BK0301
54,18327315,809517,3,BROOKLYN,1008,1008,1010,ST MARKS AVENUE,11213,ALBANY,...,550,N,40.674580,-73.938469,308,36,3324616,3013520080,343,BK0802
81,18531647,804695,1,MANHATTAN,350,350,350,EAST 124 STREET,10035,WAGNER,...,550,N,40.801536,-73.933081,111,8,1081282,1017970001,194,MN1102
66,18601457,808427,3,BROOKLYN,5817,5817,5901,GLENWOOD ROAD,11234,GLENWOOD,...,550,N,40.633639,-73.920175,318,45,3331012,3079780001,94402,BK1801
76,18539056,804634,1,MANHATTAN,435,435,435,EAST 105 STREET,10029,WILSON,...,550,N,40.788400,-73.939226,111,8,1079369,1016990001,162,MN1101
61,18334539,806882,2,BRONX,2280,2280,2280,RANDALL AVENUE,10473,CASTLE HILL,...,550,N,40.819339,-73.845573,209,18,2092636,2035370001,90,BX0903
47,18342646,806051,1,MANHATTAN,225,215,235,WEST 129 STREET,10027,SAINT NICHOLAS,...,550,N,40.811671,-73.946842,110,9,1081511,1019330050,224,MN1002
58,18370705,807996,3,BROOKLYN,35,35,53,DWIGHT STREET,11231,RED HOOK WEST,...,550,N,40.677638,-74.007138,306,38,3326974,3005330001,85,BK0601
0,18223816,286990,3,BROOKLYN,621,615,621,EAST 105 STREET,11236,BREUKELEN,...,550,N,40.650186,-73.897621,318,42,3321415,3081740001,982,BK1803

In [9]:
## How many violations are there in total? 
len(df)

109

In [16]:
## How many violations are there per borough? 
df["Primary Borough Name"].value_counts()

Primary Borough Name
BROOKLYN         45
MANHATTAN        44
BRONX            13
QUEENS            6
STATEN ISLAND     1
Name: count, dtype: int64

In [17]:
## Which developments have the most violations? 
df["Development Name"].value_counts()

Development Name
RED HOOK WEST                         10
RED HOOK EAST                          7
JOHNSON                                6
SOTOMAYOR HOUSES                       4
WAGNER                                 4
FARRAGUT                               4
ALBANY                                 4
VLADECK                                3
SHEEPSHEAD BAY                         3
WSUR (SITE A) 120 WEST 94TH STREET     3
VAN DYKE I                             3
WALD                                   3
MARCY                                  3
JEFFERSON                              2
BUTLER                                 2
DOUGLASS I                             2
CORSI HOUSES                           2
EAST RIVER                             2
BLAND                                  2
WSUR (BROWNSTONES)                     2
CONEY ISLAND I (SITES 4 & 5)           2
SAINT NICHOLAS                         2
CASTLE HILL                            2
ATLANTIC TERMINAL SITE 4B              2
RIIS II                                2
BAISLEY PARK                           2
SMITH                                  2
ASTORIA                                2
GRANT                                  2
BREUKELEN                              1
RIIS                                   1
MORRIS I                               1
GLENMORE PLAZA                         1
MOTT HAVEN                             1
STAPLETON                              1
NOSTRAND                               1
MARLBORO                               1
BRONX RIVER                            1
THROGGS NECK                           1
AMSTERDAM                              1
BARUCH                                 1
GOMPERS                                1
GLENWOOD                               1
SAINT MARY'S PARK                      1
FIRST HOUSES                           1
WILSON                                 1
CAREY GARDENS                          1
LEXINGTON                              1
GOWANUS                                1
Name: count, dtype: int64

In [22]:
## How recent is the data?
df[['Inspection Date', 'Development Name']]

    Inspection Date  Development Name
0        09/12/2025         BREUKELEN
1        10/20/2025         JEFFERSON
2        09/18/2025  SOTOMAYOR HOUSES
3        09/18/2025  SOTOMAYOR HOUSES
4        09/18/2025  SOTOMAYOR HOUSES
..              ...               ...
104      02/18/2026            BUTLER
105      02/19/2026             MARCY
106      02/24/2026             GRANT
107      02/11/2026     RED HOOK EAST
108      02/12/2026           GOWANUS

[109 rows x 2 columns]

In [31]:
## Converting to datetime
df['Inspection Date'] = pd.to_datetime(df['Inspection Date'], errors='coerce')
df

,Violation ID,Primary Building Identifier,Primary Boro Identifier,Primary Borough Name,Primary House Number,Primary Low House Number,Primary High House Number,Primary Street Name,Primary Postcode,Development Name,...,Order Number,Issued in Error,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract (2020),Neighborhood Tabulation Area (NTA) (2020)
0,18223816,286990,3,BROOKLYN,621,615,621,EAST 105 STREET,11236,BREUKELEN,...,550,N,40.650186,-73.897621,318,42,3321415,3081740001,982,BK1803
1,18311210,804658,1,MANHATTAN,218,218,220,EAST 115 STREET,10029,JEFFERSON,...,550,N,40.796972,-73.939869,111,8,1080706,1016620001,180,MN1102
2,18259184,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,Y,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
3,18235897,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,N,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
4,18235898,806350,2,BRONX,1815,1815,1815,BRUCKNER BOULEVARD,10472,SOTOMAYOR HOUSES,...,550,N,40.825724,-73.864015,209,18,2092808,2037300001,44,BX0901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,18652131,120460,2,BRONX,1320,1318,1332,WEBSTER AVENUE,10456,BUTLER,...,550,N,40.834189,-73.908540,203,16,2092074,2028940001,14701,BX0302
105,18654935,847216,3,BROOKLYN,542,542,546,FLUSHING AVENUE,11206,MARCY,...,501,N,40.699583,-73.951735,303,36,3325581,3017190001,255,BK0301
106,18662256,972853,1,MANHATTAN,3150,3140,3150,BROADWAY,10027,GRANT,...,550,N,40.814239,-73.959336,109,7,1084117,1019800001,211,MN0901
107,18635496,808526,3,BROOKLYN,811,811,817,HICKS STREET,11231,RED HOOK EAST,...,550,N,40.675324,-74.005451,306,38,3332230,3005380001,85,BK0601
108,18639299,807814,3,BROOKLYN,198,198,198,BOND STREET,11217,GOWANUS,...,550,N,40.683171,-73.987413,306,39,3323300,3003920001,71,BK0601

In [27]:
## Only looking at violatoins for 2026 
df_2026 = df[df['Inspection Date'].dt.year == 2026]

In [30]:
## Violations in 2026 by development 
df_2026["Development Name"].value_counts()

Development Name
FARRAGUT                        3
MARCY                           3
JOHNSON                         3
ATLANTIC TERMINAL SITE 4B       2
RIIS II                         2
WALD                            2
ASTORIA                         2
GRANT                           2
WAGNER                          2
RED HOOK EAST                   2
GLENWOOD                        1
CONEY ISLAND I (SITES 4 & 5)    1
SMITH                           1
CAREY GARDENS                   1
DOUGLASS I                      1
LEXINGTON                       1
RED HOOK WEST                   1
BUTLER                          1
GOWANUS                         1
Name: count, dtype: int64

In [32]:
## Only looking at violations for 2025 
df_2025 = df[df['Inspection Date'].dt.year == 2025]

In [33]:
df_2025["Development Name"].value_counts()

Development Name
RED HOOK WEST                         9
RED HOOK EAST                         5
SOTOMAYOR HOUSES                      4
ALBANY                                4
VLADECK                               3
JOHNSON                               3
SHEEPSHEAD BAY                        3
WSUR (SITE A) 120 WEST 94TH STREET    3
VAN DYKE I                            3
JEFFERSON                             2
CORSI HOUSES                          2
EAST RIVER                            2
BLAND                                 2
WSUR (BROWNSTONES)                    2
WAGNER                                2
SAINT NICHOLAS                        2
CASTLE HILL                           2
BAISLEY PARK                          2
BREUKELEN                             1
BUTLER                                1
RIIS                                  1
MORRIS I                              1
GLENMORE PLAZA                        1
DOUGLASS I                            1
MOTT HAVEN                            1
STAPLETON                             1
CONEY ISLAND I (SITES 4 & 5)          1
NOSTRAND                              1
MARLBORO                              1
BRONX RIVER                           1
THROGGS NECK                          1
AMSTERDAM                             1
FARRAGUT                              1
WALD                                  1
BARUCH                                1
GOMPERS                               1
SAINT MARY'S PARK                     1
FIRST HOUSES                          1
WILSON                                1
SMITH                                 1
Name: count, dtype: int64